/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.libiyi.exa.common.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2019-01-17")
public class TRAdminPaperAndQuestionInfo implements org.apache.thrift.TBase<TRAdminPaperAndQuestionInfo, TRAdminPaperAndQuestionInfo._Fields>, java.io.Serializable, Cloneable, Comparable<TRAdminPaperAndQuestionInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TRAdminPaperAndQuestionInfo");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField SUBJECT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("subjectId", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField CHOICE_FIELD_DESC = new org.apache.thrift.protocol.TField("choice", org.apache.thrift.protocol.TType.STRUCT, (short)4);
  private static final org.apache.thrift.protocol.TField SELECTION_FIELD_DESC = new org.apache.thrift.protocol.TField("selection", org.apache.thrift.protocol.TType.STRUCT, (short)5);
  private static final org.apache.thrift.protocol.TField FILLING_FIELD_DESC = new org.apache.thrift.protocol.TField("filling", org.apache.thrift.protocol.TType.STRUCT, (short)6);
  private static final org.apache.thrift.protocol.TField CREATE_USER_FIELD_DESC = new org.apache.thrift.protocol.TField("createUser", org.apache.thrift.protocol.TType.I32, (short)7);
  private static final org.apache.thrift.protocol.TField AVG_POINTS_FIELD_DESC = new org.apache.thrift.protocol.TField("avgPoints", org.apache.thrift.protocol.TType.I32, (short)8);
  private static final org.apache.thrift.protocol.TField COUNTS_FIELD_DESC = new org.apache.thrift.protocol.TField("counts", org.apache.thrift.protocol.TType.I32, (short)9);
  private static final org.apache.thrift.protocol.TField CREATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("createTime", org.apache.thrift.protocol.TType.I64, (short)10);
  private static final org.apache.thrift.protocol.TField UPDATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("updateTime", org.apache.thrift.protocol.TType.I64, (short)11);
  private static final org.apache.thrift.protocol.TField RESPONSE_FIELD_DESC = new org.apache.thrift.protocol.TField("response", org.apache.thrift.protocol.TType.STRUCT, (short)12);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TRAdminPaperAndQuestionInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TRAdminPaperAndQuestionInfoTupleSchemeFactory();

  public int id; // required
  public int subjectId; // required
  public String name; // required
  public TQuestionPointsAndInfoList choice; // required
  public TQuestionPointsAndInfoList selection; // required
  public TQuestionPointsAndInfoList filling; // required
  public int createUser; // required
  public int avgPoints; // required
  public int counts; // required
  public long createTime; // required
  public long updateTime; // required
  public TRResponse response; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    SUBJECT_ID((short)2, "subjectId"),
    NAME((short)3, "name"),
    CHOICE((short)4, "choice"),
    SELECTION((short)5, "selection"),
    FILLING((short)6, "filling"),
    CREATE_USER((short)7, "createUser"),
    AVG_POINTS((short)8, "avgPoints"),
    COUNTS((short)9, "counts"),
    CREATE_TIME((short)10, "createTime"),
    UPDATE_TIME((short)11, "updateTime"),
    RESPONSE((short)12, "response");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // SUBJECT_ID
          return SUBJECT_ID;
        case 3: // NAME
          return NAME;
        case 4: // CHOICE
          return CHOICE;
        case 5: // SELECTION
          return SELECTION;
        case 6: // FILLING
          return FILLING;
        case 7: // CREATE_USER
          return CREATE_USER;
        case 8: // AVG_POINTS
          return AVG_POINTS;
        case 9: // COUNTS
          return COUNTS;
        case 10: // CREATE_TIME
          return CREATE_TIME;
        case 11: // UPDATE_TIME
          return UPDATE_TIME;
        case 12: // RESPONSE
          return RESPONSE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __SUBJECTID_ISSET_ID = 1;
  private static final int __CREATEUSER_ISSET_ID = 2;
  private static final int __AVGPOINTS_ISSET_ID = 3;
  private static final int __COUNTS_ISSET_ID = 4;
  private static final int __CREATETIME_ISSET_ID = 5;
  private static final int __UPDATETIME_ISSET_ID = 6;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SUBJECT_ID, new org.apache.thrift.meta_data.FieldMetaData("subjectId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CHOICE, new org.apache.thrift.meta_data.FieldMetaData("choice", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "TQuestionPointsAndInfoList")));
    tmpMap.put(_Fields.SELECTION, new org.apache.thrift.meta_data.FieldMetaData("selection", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "TQuestionPointsAndInfoList")));
    tmpMap.put(_Fields.FILLING, new org.apache.thrift.meta_data.FieldMetaData("filling", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "TQuestionPointsAndInfoList")));
    tmpMap.put(_Fields.CREATE_USER, new org.apache.thrift.meta_data.FieldMetaData("createUser", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.AVG_POINTS, new org.apache.thrift.meta_data.FieldMetaData("avgPoints", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.COUNTS, new org.apache.thrift.meta_data.FieldMetaData("counts", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CREATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("createTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.UPDATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("updateTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.RESPONSE, new org.apache.thrift.meta_data.FieldMetaData("response", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TRResponse.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TRAdminPaperAndQuestionInfo.class, metaDataMap);
  }

  public TRAdminPaperAndQuestionInfo() {
  }

  public TRAdminPaperAndQuestionInfo(
    int id,
    int subjectId,
    String name,
    TQuestionPointsAndInfoList choice,
    TQuestionPointsAndInfoList selection,
    TQuestionPointsAndInfoList filling,
    int createUser,
    int avgPoints,
    int counts,
    long createTime,
    long updateTime,
    TRResponse response)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.subjectId = subjectId;
    setSubjectIdIsSet(true);
    this.name = name;
    this.choice = choice;
    this.selection = selection;
    this.filling = filling;
    this.createUser = createUser;
    setCreateUserIsSet(true);
    this.avgPoints = avgPoints;
    setAvgPointsIsSet(true);
    this.counts = counts;
    setCountsIsSet(true);
    this.createTime = createTime;
    setCreateTimeIsSet(true);
    this.updateTime = updateTime;
    setUpdateTimeIsSet(true);
    this.response = response;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TRAdminPaperAndQuestionInfo(TRAdminPaperAndQuestionInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    this.subjectId = other.subjectId;
    if (other.isSetName()) {
      this.name = other.name;
    }
    if (other.isSetChoice()) {
      this.choice = new TQuestionPointsAndInfoList(other.choice);
    }
    if (other.isSetSelection()) {
      this.selection = new TQuestionPointsAndInfoList(other.selection);
    }
    if (other.isSetFilling()) {
      this.filling = new TQuestionPointsAndInfoList(other.filling);
    }
    this.createUser = other.createUser;
    this.avgPoints = other.avgPoints;
    this.counts = other.counts;
    this.createTime = other.createTime;
    this.updateTime = other.updateTime;
    if (other.isSetResponse()) {
      this.response = new TRResponse(other.response);
    }
  }

  public TRAdminPaperAndQuestionInfo deepCopy() {
    return new TRAdminPaperAndQuestionInfo(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    setSubjectIdIsSet(false);
    this.subjectId = 0;
    this.name = null;
    this.choice = null;
    this.selection = null;
    this.filling = null;
    setCreateUserIsSet(false);
    this.createUser = 0;
    setAvgPointsIsSet(false);
    this.avgPoints = 0;
    setCountsIsSet(false);
    this.counts = 0;
    setCreateTimeIsSet(false);
    this.createTime = 0;
    setUpdateTimeIsSet(false);
    this.updateTime = 0;
    this.response = null;
  }

  public int getId() {
    return this.id;
  }

  public TRAdminPaperAndQuestionInfo setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public int getSubjectId() {
    return this.subjectId;
  }

  public TRAdminPaperAndQuestionInfo setSubjectId(int subjectId) {
    this.subjectId = subjectId;
    setSubjectIdIsSet(true);
    return this;
  }

  public void unsetSubjectId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SUBJECTID_ISSET_ID);
  }

  /** Returns true if field subjectId is set (has been assigned a value) and false otherwise */
  public boolean isSetSubjectId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SUBJECTID_ISSET_ID);
  }

  public void setSubjectIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SUBJECTID_ISSET_ID, value);
  }

  public String getName() {
    return this.name;
  }

  public TRAdminPaperAndQuestionInfo setName(String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public TQuestionPointsAndInfoList getChoice() {
    return this.choice;
  }

  public TRAdminPaperAndQuestionInfo setChoice(TQuestionPointsAndInfoList choice) {
    this.choice = choice;
    return this;
  }

  public void unsetChoice() {
    this.choice = null;
  }

  /** Returns true if field choice is set (has been assigned a value) and false otherwise */
  public boolean isSetChoice() {
    return this.choice != null;
  }

  public void setChoiceIsSet(boolean value) {
    if (!value) {
      this.choice = null;
    }
  }

  public TQuestionPointsAndInfoList getSelection() {
    return this.selection;
  }

  public TRAdminPaperAndQuestionInfo setSelection(TQuestionPointsAndInfoList selection) {
    this.selection = selection;
    return this;
  }

  public void unsetSelection() {
    this.selection = null;
  }

  /** Returns true if field selection is set (has been assigned a value) and false otherwise */
  public boolean isSetSelection() {
    return this.selection != null;
  }

  public void setSelectionIsSet(boolean value) {
    if (!value) {
      this.selection = null;
    }
  }

  public TQuestionPointsAndInfoList getFilling() {
    return this.filling;
  }

  public TRAdminPaperAndQuestionInfo setFilling(TQuestionPointsAndInfoList filling) {
    this.filling = filling;
    return this;
  }

  public void unsetFilling() {
    this.filling = null;
  }

  /** Returns true if field filling is set (has been assigned a value) and false otherwise */
  public boolean isSetFilling() {
    return this.filling != null;
  }

  public void setFillingIsSet(boolean value) {
    if (!value) {
      this.filling = null;
    }
  }

  public int getCreateUser() {
    return this.createUser;
  }

  public TRAdminPaperAndQuestionInfo setCreateUser(int createUser) {
    this.createUser = createUser;
    setCreateUserIsSet(true);
    return this;
  }

  public void unsetCreateUser() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATEUSER_ISSET_ID);
  }

  /** Returns true if field createUser is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateUser() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATEUSER_ISSET_ID);
  }

  public void setCreateUserIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATEUSER_ISSET_ID, value);
  }

  public int getAvgPoints() {
    return this.avgPoints;
  }

  public TRAdminPaperAndQuestionInfo setAvgPoints(int avgPoints) {
    this.avgPoints = avgPoints;
    setAvgPointsIsSet(true);
    return this;
  }

  public void unsetAvgPoints() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __AVGPOINTS_ISSET_ID);
  }

  /** Returns true if field avgPoints is set (has been assigned a value) and false otherwise */
  public boolean isSetAvgPoints() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __AVGPOINTS_ISSET_ID);
  }

  public void setAvgPointsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __AVGPOINTS_ISSET_ID, value);
  }

  public int getCounts() {
    return this.counts;
  }

  public TRAdminPaperAndQuestionInfo setCounts(int counts) {
    this.counts = counts;
    setCountsIsSet(true);
    return this;
  }

  public void unsetCounts() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __COUNTS_ISSET_ID);
  }

  /** Returns true if field counts is set (has been assigned a value) and false otherwise */
  public boolean isSetCounts() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __COUNTS_ISSET_ID);
  }

  public void setCountsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __COUNTS_ISSET_ID, value);
  }

  public long getCreateTime() {
    return this.createTime;
  }

  public TRAdminPaperAndQuestionInfo setCreateTime(long createTime) {
    this.createTime = createTime;
    setCreateTimeIsSet(true);
    return this;
  }

  public void unsetCreateTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  /** Returns true if field createTime is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  public void setCreateTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATETIME_ISSET_ID, value);
  }

  public long getUpdateTime() {
    return this.updateTime;
  }

  public TRAdminPaperAndQuestionInfo setUpdateTime(long updateTime) {
    this.updateTime = updateTime;
    setUpdateTimeIsSet(true);
    return this;
  }

  public void unsetUpdateTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __UPDATETIME_ISSET_ID);
  }

  /** Returns true if field updateTime is set (has been assigned a value) and false otherwise */
  public boolean isSetUpdateTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __UPDATETIME_ISSET_ID);
  }

  public void setUpdateTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __UPDATETIME_ISSET_ID, value);
  }

  public TRResponse getResponse() {
    return this.response;
  }

  public TRAdminPaperAndQuestionInfo setResponse(TRResponse response) {
    this.response = response;
    return this;
  }

  public void unsetResponse() {
    this.response = null;
  }

  /** Returns true if field response is set (has been assigned a value) and false otherwise */
  public boolean isSetResponse() {
    return this.response != null;
  }

  public void setResponseIsSet(boolean value) {
    if (!value) {
      this.response = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((Integer)value);
      }
      break;

    case SUBJECT_ID:
      if (value == null) {
        unsetSubjectId();
      } else {
        setSubjectId((Integer)value);
      }
      break;

    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((String)value);
      }
      break;

    case CHOICE:
      if (value == null) {
        unsetChoice();
      } else {
        setChoice((TQuestionPointsAndInfoList)value);
      }
      break;

    case SELECTION:
      if (value == null) {
        unsetSelection();
      } else {
        setSelection((TQuestionPointsAndInfoList)value);
      }
      break;

    case FILLING:
      if (value == null) {
        unsetFilling();
      } else {
        setFilling((TQuestionPointsAndInfoList)value);
      }
      break;

    case CREATE_USER:
      if (value == null) {
        unsetCreateUser();
      } else {
        setCreateUser((Integer)value);
      }
      break;

    case AVG_POINTS:
      if (value == null) {
        unsetAvgPoints();
      } else {
        setAvgPoints((Integer)value);
      }
      break;

    case COUNTS:
      if (value == null) {
        unsetCounts();
      } else {
        setCounts((Integer)value);
      }
      break;

    case CREATE_TIME:
      if (value == null) {
        unsetCreateTime();
      } else {
        setCreateTime((Long)value);
      }
      break;

    case UPDATE_TIME:
      if (value == null) {
        unsetUpdateTime();
      } else {
        setUpdateTime((Long)value);
      }
      break;

    case RESPONSE:
      if (value == null) {
        unsetResponse();
      } else {
        setResponse((TRResponse)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case SUBJECT_ID:
      return getSubjectId();

    case NAME:
      return getName();

    case CHOICE:
      return getChoice();

    case SELECTION:
      return getSelection();

    case FILLING:
      return getFilling();

    case CREATE_USER:
      return getCreateUser();

    case AVG_POINTS:
      return getAvgPoints();

    case COUNTS:
      return getCounts();

    case CREATE_TIME:
      return getCreateTime();

    case UPDATE_TIME:
      return getUpdateTime();

    case RESPONSE:
      return getResponse();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case SUBJECT_ID:
      return isSetSubjectId();
    case NAME:
      return isSetName();
    case CHOICE:
      return isSetChoice();
    case SELECTION:
      return isSetSelection();
    case FILLING:
      return isSetFilling();
    case CREATE_USER:
      return isSetCreateUser();
    case AVG_POINTS:
      return isSetAvgPoints();
    case COUNTS:
      return isSetCounts();
    case CREATE_TIME:
      return isSetCreateTime();
    case UPDATE_TIME:
      return isSetUpdateTime();
    case RESPONSE:
      return isSetResponse();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TRAdminPaperAndQuestionInfo)
      return this.equals((TRAdminPaperAndQuestionInfo)that);
    return false;
  }

  public boolean equals(TRAdminPaperAndQuestionInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_subjectId = true;
    boolean that_present_subjectId = true;
    if (this_present_subjectId || that_present_subjectId) {
      if (!(this_present_subjectId && that_present_subjectId))
        return false;
      if (this.subjectId != that.subjectId)
        return false;
    }

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_choice = true && this.isSetChoice();
    boolean that_present_choice = true && that.isSetChoice();
    if (this_present_choice || that_present_choice) {
      if (!(this_present_choice && that_present_choice))
        return false;
      if (!this.choice.equals(that.choice))
        return false;
    }

    boolean this_present_selection = true && this.isSetSelection();
    boolean that_present_selection = true && that.isSetSelection();
    if (this_present_selection || that_present_selection) {
      if (!(this_present_selection && that_present_selection))
        return false;
      if (!this.selection.equals(that.selection))
        return false;
    }

    boolean this_present_filling = true && this.isSetFilling();
    boolean that_present_filling = true && that.isSetFilling();
    if (this_present_filling || that_present_filling) {
      if (!(this_present_filling && that_present_filling))
        return false;
      if (!this.filling.equals(that.filling))
        return false;
    }

    boolean this_present_createUser = true;
    boolean that_present_createUser = true;
    if (this_present_createUser || that_present_createUser) {
      if (!(this_present_createUser && that_present_createUser))
        return false;
      if (this.createUser != that.createUser)
        return false;
    }

    boolean this_present_avgPoints = true;
    boolean that_present_avgPoints = true;
    if (this_present_avgPoints || that_present_avgPoints) {
      if (!(this_present_avgPoints && that_present_avgPoints))
        return false;
      if (this.avgPoints != that.avgPoints)
        return false;
    }

    boolean this_present_counts = true;
    boolean that_present_counts = true;
    if (this_present_counts || that_present_counts) {
      if (!(this_present_counts && that_present_counts))
        return false;
      if (this.counts != that.counts)
        return false;
    }

    boolean this_present_createTime = true;
    boolean that_present_createTime = true;
    if (this_present_createTime || that_present_createTime) {
      if (!(this_present_createTime && that_present_createTime))
        return false;
      if (this.createTime != that.createTime)
        return false;
    }

    boolean this_present_updateTime = true;
    boolean that_present_updateTime = true;
    if (this_present_updateTime || that_present_updateTime) {
      if (!(this_present_updateTime && that_present_updateTime))
        return false;
      if (this.updateTime != that.updateTime)
        return false;
    }

    boolean this_present_response = true && this.isSetResponse();
    boolean that_present_response = true && that.isSetResponse();
    if (this_present_response || that_present_response) {
      if (!(this_present_response && that_present_response))
        return false;
      if (!this.response.equals(that.response))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + id;

    hashCode = hashCode * 8191 + subjectId;

    hashCode = hashCode * 8191 + ((isSetName()) ? 131071 : 524287);
    if (isSetName())
      hashCode = hashCode * 8191 + name.hashCode();

    hashCode = hashCode * 8191 + ((isSetChoice()) ? 131071 : 524287);
    if (isSetChoice())
      hashCode = hashCode * 8191 + choice.hashCode();

    hashCode = hashCode * 8191 + ((isSetSelection()) ? 131071 : 524287);
    if (isSetSelection())
      hashCode = hashCode * 8191 + selection.hashCode();

    hashCode = hashCode * 8191 + ((isSetFilling()) ? 131071 : 524287);
    if (isSetFilling())
      hashCode = hashCode * 8191 + filling.hashCode();

    hashCode = hashCode * 8191 + createUser;

    hashCode = hashCode * 8191 + avgPoints;

    hashCode = hashCode * 8191 + counts;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(createTime);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(updateTime);

    hashCode = hashCode * 8191 + ((isSetResponse()) ? 131071 : 524287);
    if (isSetResponse())
      hashCode = hashCode * 8191 + response.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TRAdminPaperAndQuestionInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSubjectId()).compareTo(other.isSetSubjectId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSubjectId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.subjectId, other.subjectId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetChoice()).compareTo(other.isSetChoice());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetChoice()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.choice, other.choice);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSelection()).compareTo(other.isSetSelection());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSelection()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.selection, other.selection);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFilling()).compareTo(other.isSetFilling());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFilling()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.filling, other.filling);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreateUser()).compareTo(other.isSetCreateUser());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateUser()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createUser, other.createUser);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAvgPoints()).compareTo(other.isSetAvgPoints());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAvgPoints()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.avgPoints, other.avgPoints);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCounts()).compareTo(other.isSetCounts());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCounts()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.counts, other.counts);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreateTime()).compareTo(other.isSetCreateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTime, other.createTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUpdateTime()).compareTo(other.isSetUpdateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUpdateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.updateTime, other.updateTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetResponse()).compareTo(other.isSetResponse());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponse()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.response, other.response);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TRAdminPaperAndQuestionInfo(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("subjectId:");
    sb.append(this.subjectId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("choice:");
    if (this.choice == null) {
      sb.append("null");
    } else {
      sb.append(this.choice);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("selection:");
    if (this.selection == null) {
      sb.append("null");
    } else {
      sb.append(this.selection);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("filling:");
    if (this.filling == null) {
      sb.append("null");
    } else {
      sb.append(this.filling);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("createUser:");
    sb.append(this.createUser);
    first = false;
    if (!first) sb.append(", ");
    sb.append("avgPoints:");
    sb.append(this.avgPoints);
    first = false;
    if (!first) sb.append(", ");
    sb.append("counts:");
    sb.append(this.counts);
    first = false;
    if (!first) sb.append(", ");
    sb.append("createTime:");
    sb.append(this.createTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("updateTime:");
    sb.append(this.updateTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("response:");
    if (this.response == null) {
      sb.append("null");
    } else {
      sb.append(this.response);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (response != null) {
      response.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TRAdminPaperAndQuestionInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TRAdminPaperAndQuestionInfoStandardScheme getScheme() {
      return new TRAdminPaperAndQuestionInfoStandardScheme();
    }
  }

  private static class TRAdminPaperAndQuestionInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<TRAdminPaperAndQuestionInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TRAdminPaperAndQuestionInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SUBJECT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.subjectId = iprot.readI32();
              struct.setSubjectIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CHOICE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.choice = new TQuestionPointsAndInfoList();
              struct.choice.read(iprot);
              struct.setChoiceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // SELECTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.selection = new TQuestionPointsAndInfoList();
              struct.selection.read(iprot);
              struct.setSelectionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // FILLING
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.filling = new TQuestionPointsAndInfoList();
              struct.filling.read(iprot);
              struct.setFillingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // CREATE_USER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.createUser = iprot.readI32();
              struct.setCreateUserIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // AVG_POINTS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.avgPoints = iprot.readI32();
              struct.setAvgPointsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // COUNTS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.counts = iprot.readI32();
              struct.setCountsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // CREATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createTime = iprot.readI64();
              struct.setCreateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // UPDATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.updateTime = iprot.readI64();
              struct.setUpdateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // RESPONSE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.response = new TRResponse();
              struct.response.read(iprot);
              struct.setResponseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TRAdminPaperAndQuestionInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SUBJECT_ID_FIELD_DESC);
      oprot.writeI32(struct.subjectId);
      oprot.writeFieldEnd();
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      if (struct.choice != null) {
        oprot.writeFieldBegin(CHOICE_FIELD_DESC);
        struct.choice.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.selection != null) {
        oprot.writeFieldBegin(SELECTION_FIELD_DESC);
        struct.selection.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.filling != null) {
        oprot.writeFieldBegin(FILLING_FIELD_DESC);
        struct.filling.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(CREATE_USER_FIELD_DESC);
      oprot.writeI32(struct.createUser);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(AVG_POINTS_FIELD_DESC);
      oprot.writeI32(struct.avgPoints);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(COUNTS_FIELD_DESC);
      oprot.writeI32(struct.counts);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CREATE_TIME_FIELD_DESC);
      oprot.writeI64(struct.createTime);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(UPDATE_TIME_FIELD_DESC);
      oprot.writeI64(struct.updateTime);
      oprot.writeFieldEnd();
      if (struct.response != null) {
        oprot.writeFieldBegin(RESPONSE_FIELD_DESC);
        struct.response.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TRAdminPaperAndQuestionInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TRAdminPaperAndQuestionInfoTupleScheme getScheme() {
      return new TRAdminPaperAndQuestionInfoTupleScheme();
    }
  }

  private static class TRAdminPaperAndQuestionInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<TRAdminPaperAndQuestionInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TRAdminPaperAndQuestionInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetSubjectId()) {
        optionals.set(1);
      }
      if (struct.isSetName()) {
        optionals.set(2);
      }
      if (struct.isSetChoice()) {
        optionals.set(3);
      }
      if (struct.isSetSelection()) {
        optionals.set(4);
      }
      if (struct.isSetFilling()) {
        optionals.set(5);
      }
      if (struct.isSetCreateUser()) {
        optionals.set(6);
      }
      if (struct.isSetAvgPoints()) {
        optionals.set(7);
      }
      if (struct.isSetCounts()) {
        optionals.set(8);
      }
      if (struct.isSetCreateTime()) {
        optionals.set(9);
      }
      if (struct.isSetUpdateTime()) {
        optionals.set(10);
      }
      if (struct.isSetResponse()) {
        optionals.set(11);
      }
      oprot.writeBitSet(optionals, 12);
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetSubjectId()) {
        oprot.writeI32(struct.subjectId);
      }
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
      if (struct.isSetChoice()) {
        struct.choice.write(oprot);
      }
      if (struct.isSetSelection()) {
        struct.selection.write(oprot);
      }
      if (struct.isSetFilling()) {
        struct.filling.write(oprot);
      }
      if (struct.isSetCreateUser()) {
        oprot.writeI32(struct.createUser);
      }
      if (struct.isSetAvgPoints()) {
        oprot.writeI32(struct.avgPoints);
      }
      if (struct.isSetCounts()) {
        oprot.writeI32(struct.counts);
      }
      if (struct.isSetCreateTime()) {
        oprot.writeI64(struct.createTime);
      }
      if (struct.isSetUpdateTime()) {
        oprot.writeI64(struct.updateTime);
      }
      if (struct.isSetResponse()) {
        struct.response.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TRAdminPaperAndQuestionInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(12);
      if (incoming.get(0)) {
        struct.id = iprot.readI32();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.subjectId = iprot.readI32();
        struct.setSubjectIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.choice = new TQuestionPointsAndInfoList();
        struct.choice.read(iprot);
        struct.setChoiceIsSet(true);
      }
      if (incoming.get(4)) {
        struct.selection = new TQuestionPointsAndInfoList();
        struct.selection.read(iprot);
        struct.setSelectionIsSet(true);
      }
      if (incoming.get(5)) {
        struct.filling = new TQuestionPointsAndInfoList();
        struct.filling.read(iprot);
        struct.setFillingIsSet(true);
      }
      if (incoming.get(6)) {
        struct.createUser = iprot.readI32();
        struct.setCreateUserIsSet(true);
      }
      if (incoming.get(7)) {
        struct.avgPoints = iprot.readI32();
        struct.setAvgPointsIsSet(true);
      }
      if (incoming.get(8)) {
        struct.counts = iprot.readI32();
        struct.setCountsIsSet(true);
      }
      if (incoming.get(9)) {
        struct.createTime = iprot.readI64();
        struct.setCreateTimeIsSet(true);
      }
      if (incoming.get(10)) {
        struct.updateTime = iprot.readI64();
        struct.setUpdateTimeIsSet(true);
      }
      if (incoming.get(11)) {
        struct.response = new TRResponse();
        struct.response.read(iprot);
        struct.setResponseIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

