/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.libiyi.exa.common.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2019-03-04")
public class TRPracticeRecord implements org.apache.thrift.TBase<TRPracticeRecord, TRPracticeRecord._Fields>, java.io.Serializable, Cloneable, Comparable<TRPracticeRecord> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TRPracticeRecord");

  private static final org.apache.thrift.protocol.TField RESPONSE_FIELD_DESC = new org.apache.thrift.protocol.TField("response", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField PRACTICE_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("practiceInfo", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TRPracticeRecordStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TRPracticeRecordTupleSchemeFactory();

  public TRResponse response; // required
  public java.util.List<TPracticeRecordAndPaperInfo> practiceInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RESPONSE((short)1, "response"),
    PRACTICE_INFO((short)2, "practiceInfo");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESPONSE
          return RESPONSE;
        case 2: // PRACTICE_INFO
          return PRACTICE_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESPONSE, new org.apache.thrift.meta_data.FieldMetaData("response", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TRResponse.class)));
    tmpMap.put(_Fields.PRACTICE_INFO, new org.apache.thrift.meta_data.FieldMetaData("practiceInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT            , "TPracticeRecordAndPaperInfo"))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TRPracticeRecord.class, metaDataMap);
  }

  public TRPracticeRecord() {
  }

  public TRPracticeRecord(
    TRResponse response,
    java.util.List<TPracticeRecordAndPaperInfo> practiceInfo)
  {
    this();
    this.response = response;
    this.practiceInfo = practiceInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TRPracticeRecord(TRPracticeRecord other) {
    if (other.isSetResponse()) {
      this.response = new TRResponse(other.response);
    }
    if (other.isSetPracticeInfo()) {
      java.util.List<TPracticeRecordAndPaperInfo> __this__practiceInfo = new java.util.ArrayList<TPracticeRecordAndPaperInfo>(other.practiceInfo.size());
      for (TPracticeRecordAndPaperInfo other_element : other.practiceInfo) {
        __this__practiceInfo.add(new TPracticeRecordAndPaperInfo(other_element));
      }
      this.practiceInfo = __this__practiceInfo;
    }
  }

  public TRPracticeRecord deepCopy() {
    return new TRPracticeRecord(this);
  }

  @Override
  public void clear() {
    this.response = null;
    this.practiceInfo = null;
  }

  public TRResponse getResponse() {
    return this.response;
  }

  public TRPracticeRecord setResponse(TRResponse response) {
    this.response = response;
    return this;
  }

  public void unsetResponse() {
    this.response = null;
  }

  /** Returns true if field response is set (has been assigned a value) and false otherwise */
  public boolean isSetResponse() {
    return this.response != null;
  }

  public void setResponseIsSet(boolean value) {
    if (!value) {
      this.response = null;
    }
  }

  public int getPracticeInfoSize() {
    return (this.practiceInfo == null) ? 0 : this.practiceInfo.size();
  }

  public java.util.Iterator<TPracticeRecordAndPaperInfo> getPracticeInfoIterator() {
    return (this.practiceInfo == null) ? null : this.practiceInfo.iterator();
  }

  public void addToPracticeInfo(TPracticeRecordAndPaperInfo elem) {
    if (this.practiceInfo == null) {
      this.practiceInfo = new java.util.ArrayList<TPracticeRecordAndPaperInfo>();
    }
    this.practiceInfo.add(elem);
  }

  public java.util.List<TPracticeRecordAndPaperInfo> getPracticeInfo() {
    return this.practiceInfo;
  }

  public TRPracticeRecord setPracticeInfo(java.util.List<TPracticeRecordAndPaperInfo> practiceInfo) {
    this.practiceInfo = practiceInfo;
    return this;
  }

  public void unsetPracticeInfo() {
    this.practiceInfo = null;
  }

  /** Returns true if field practiceInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetPracticeInfo() {
    return this.practiceInfo != null;
  }

  public void setPracticeInfoIsSet(boolean value) {
    if (!value) {
      this.practiceInfo = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RESPONSE:
      if (value == null) {
        unsetResponse();
      } else {
        setResponse((TRResponse)value);
      }
      break;

    case PRACTICE_INFO:
      if (value == null) {
        unsetPracticeInfo();
      } else {
        setPracticeInfo((java.util.List<TPracticeRecordAndPaperInfo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESPONSE:
      return getResponse();

    case PRACTICE_INFO:
      return getPracticeInfo();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESPONSE:
      return isSetResponse();
    case PRACTICE_INFO:
      return isSetPracticeInfo();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TRPracticeRecord)
      return this.equals((TRPracticeRecord)that);
    return false;
  }

  public boolean equals(TRPracticeRecord that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_response = true && this.isSetResponse();
    boolean that_present_response = true && that.isSetResponse();
    if (this_present_response || that_present_response) {
      if (!(this_present_response && that_present_response))
        return false;
      if (!this.response.equals(that.response))
        return false;
    }

    boolean this_present_practiceInfo = true && this.isSetPracticeInfo();
    boolean that_present_practiceInfo = true && that.isSetPracticeInfo();
    if (this_present_practiceInfo || that_present_practiceInfo) {
      if (!(this_present_practiceInfo && that_present_practiceInfo))
        return false;
      if (!this.practiceInfo.equals(that.practiceInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetResponse()) ? 131071 : 524287);
    if (isSetResponse())
      hashCode = hashCode * 8191 + response.hashCode();

    hashCode = hashCode * 8191 + ((isSetPracticeInfo()) ? 131071 : 524287);
    if (isSetPracticeInfo())
      hashCode = hashCode * 8191 + practiceInfo.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TRPracticeRecord other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetResponse()).compareTo(other.isSetResponse());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponse()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.response, other.response);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPracticeInfo()).compareTo(other.isSetPracticeInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPracticeInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.practiceInfo, other.practiceInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TRPracticeRecord(");
    boolean first = true;

    sb.append("response:");
    if (this.response == null) {
      sb.append("null");
    } else {
      sb.append(this.response);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("practiceInfo:");
    if (this.practiceInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.practiceInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (response != null) {
      response.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TRPracticeRecordStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TRPracticeRecordStandardScheme getScheme() {
      return new TRPracticeRecordStandardScheme();
    }
  }

  private static class TRPracticeRecordStandardScheme extends org.apache.thrift.scheme.StandardScheme<TRPracticeRecord> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TRPracticeRecord struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESPONSE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.response = new TRResponse();
              struct.response.read(iprot);
              struct.setResponseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PRACTICE_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list110 = iprot.readListBegin();
                struct.practiceInfo = new java.util.ArrayList<TPracticeRecordAndPaperInfo>(_list110.size);
                TPracticeRecordAndPaperInfo _elem111;
                for (int _i112 = 0; _i112 < _list110.size; ++_i112)
                {
                  _elem111 = new TPracticeRecordAndPaperInfo();
                  _elem111.read(iprot);
                  struct.practiceInfo.add(_elem111);
                }
                iprot.readListEnd();
              }
              struct.setPracticeInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TRPracticeRecord struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.response != null) {
        oprot.writeFieldBegin(RESPONSE_FIELD_DESC);
        struct.response.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.practiceInfo != null) {
        oprot.writeFieldBegin(PRACTICE_INFO_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.practiceInfo.size()));
          for (TPracticeRecordAndPaperInfo _iter113 : struct.practiceInfo)
          {
            _iter113.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TRPracticeRecordTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TRPracticeRecordTupleScheme getScheme() {
      return new TRPracticeRecordTupleScheme();
    }
  }

  private static class TRPracticeRecordTupleScheme extends org.apache.thrift.scheme.TupleScheme<TRPracticeRecord> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TRPracticeRecord struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetResponse()) {
        optionals.set(0);
      }
      if (struct.isSetPracticeInfo()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetResponse()) {
        struct.response.write(oprot);
      }
      if (struct.isSetPracticeInfo()) {
        {
          oprot.writeI32(struct.practiceInfo.size());
          for (TPracticeRecordAndPaperInfo _iter114 : struct.practiceInfo)
          {
            _iter114.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TRPracticeRecord struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.response = new TRResponse();
        struct.response.read(iprot);
        struct.setResponseIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list115 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.practiceInfo = new java.util.ArrayList<TPracticeRecordAndPaperInfo>(_list115.size);
          TPracticeRecordAndPaperInfo _elem116;
          for (int _i117 = 0; _i117 < _list115.size; ++_i117)
          {
            _elem116 = new TPracticeRecordAndPaperInfo();
            _elem116.read(iprot);
            struct.practiceInfo.add(_elem116);
          }
        }
        struct.setPracticeInfoIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

